apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpet-test
  labels:
    app: jpet-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpet-test
  template:
    metadata:
      labels:
        app: jpet-test
    spec:
      containers:
      - name: jpet-test
        image: 172.30.1.186:30003/jpettest/final:0.1-8807520
        ports:
        - containerPort: 8080
