apiVersion: v1
kind: Service
metadata:
  name: jpet-service
  labels:
    app: jpet-test
spec:
  selector:
    app: jpet-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
