apiVersion: v1
kind: Service
metadata:
  name: jpet-service
  labels:
    app: jpet-test
spec:
  type: NodePort
  selector:
    matchLabels:
      app: jpet-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
